"""Созданы таблицы для игры, кликов и статистики

Revision ID: 916c14075885
Revises: 627e3a5c2e02
Create Date: 2025-05-01 18:03:44.242784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916c14075885'
down_revision: Union[str, None] = '627e3a5c2e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_table('clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('successful', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clicks_id'), 'clicks', ['id'], unique=False)
    op.create_table('game_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Boolean(), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('successful_clicks', sa.Integer(), nullable=True),
    sa.Column('failed_clicks', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_statistics_id'), 'game_statistics', ['id'], unique=False)
    op.add_column('users', sa.Column('games_played', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_clicks', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('successful_clicks', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('failed_clicks', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('most_used_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'most_used_color')
    op.drop_column('users', 'failed_clicks')
    op.drop_column('users', 'successful_clicks')
    op.drop_column('users', 'total_clicks')
    op.drop_column('users', 'games_played')
    op.drop_index(op.f('ix_game_statistics_id'), table_name='game_statistics')
    op.drop_table('game_statistics')
    op.drop_index(op.f('ix_clicks_id'), table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
